# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TipForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipForm(object):
    def setupUi(self, TipForm):
        TipForm.setObjectName("TipForm")
        TipForm.resize(335, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TipForm.sizePolicy().hasHeightForWidth())
        TipForm.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(TipForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TipForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(TipForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pt_search = QtWidgets.QPlainTextEdit(self.widget)
        self.pt_search.setObjectName("pt_search")
        self.horizontalLayout.addWidget(self.pt_search)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(TipForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_save = QtWidgets.QPushButton(self.widget_2)
        self.pb_save.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_2.addWidget(self.pb_save, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(TipForm)
        self.pb_save.clicked.connect(TipForm.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TipForm)

    def retranslateUi(self, TipForm):
        _translate = QtCore.QCoreApplication.translate
        TipForm.setWindowTitle(_translate("TipForm", "配置角色名称"))
        self.label.setText(_translate("TipForm", "<html><head/><body><p>输入你<span style=\" font-weight:600; color:#f30752;\">拥有的</span>屠夫名称，排除你<span style=\" font-weight:600; color:#ff5500;\">未拥有的</span>以及<span style=\" font-weight:600; color:#ffaa00;\">被禁用</span></p><p><span style=\" font-weight:600; color:#ffaa00;\">的</span>屠夫名称。<span style=\" font-weight:600;\">不留空行</span></p><p>每当你的屠夫<span style=\" font-weight:600; color:#00aaff;\">数量变化时</span>，都应该<span style=\" font-size:10pt; font-weight:600;\">重新配置</span>。</p><p>如果<span style=\" font-weight:600; color:#00aa00;\">只选择一个角色</span>挂机则无需配置。</p></body></html>"))
        self.pb_save.setText(_translate("TipForm", "保 存"))
